export default Object.freeze({
    ABOUT_US: 'About Us',
    ACCOUNT: 'Accounts',
    APPLICATION_PROCEDURE: 'Application Procedure',
    BUY_APPLICATION: 'Buy Application',
    CUSTOMER_SUPPORT: 'Customer Support',
    ELIGIBILITY: 'Eligibility Criteria',
    FAQ: 'FAQ',
    GENERAL_INQUIRIES: 'General Inquiries',
    HELP_ME_FIND_HOME: 'Help Me Find A Home',
    HOUSING_DEVELOPMENTS: 'Housing Developments',
    RENT_APPLICATION: 'Rent Application',
    INFORMATION_CENTER:'Information Center',
    MAINTENANCE: 'Maintain',
    MY_MAINTENANCE: 'My Maintenance',
    MY_PAYMENTS: 'My Payments',
    MY_LISTINGS: 'My Listings',
    MY_PROPERTY: 'My Property',
    NOTIFICATIONS: 'Notifications',
    PAYMENTS: 'Payment',
    PRODUCTS: 'BHC Products',
    PROPERTY_DETAILS: 'Property Details',
    PROPERTY_LISTINGS: 'Properties Listings',
    PROPERTIES: 'Property'
})